# trigger the build: 1
name: vhs
on:
  push:
    paths:
      - assets/demo.tape

permissions:
  contents: write # Allow writing releases

jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download jujuid
        run: |
          gh release download --repo jzandbergen/jujuid --pattern 'jujuid-linux-amd64' --dir /tmp
          chmod +x /tmp/jujuid-linux-amd64
          sudo mv /tmp/jujuid-linux-amd64 /usr/local/bin/jujuid
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: charmbracelet/vhs-action@v2
        with:
          path: 'assets/demo.tape'
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'docs(vhs): update demo.gif'
          branch: main
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: '*.gif'
